iot/lista_5/lib/__init__.py
import logging
from typing import List
logger = logging.getLogger('app')
logger.setLevel(logging.DEBUG)

# create console handler and set level to debug
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter('[%(asctime)s] %(name)s - %(levelname)s - %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)

import ssl
import certifi

sslcontext = ssl.create_default_context(cafile=certifi.where())

from quart import Quart
from .service import Manager, Service

manager = Manager()

def create_app(services: List[Service]) -> Quart:
    from .views import controller, static

    for item in services:
        manager[item.name] = item
    
    app = Quart(__name__)

    app.register_blueprint(controller)
    app.register_blueprint(static)

    logger.info("creating app")
    return app

iot/lista_5/lib/views.py
import asyncio
from logging import Filter
from quart import Blueprint, json, jsonify, request, render_template, send_file, send_from_directory, redirect
from .service import Generator, Aggregator, FilterGenerator, GraphingAggregator
from werkzeug.exceptions import NotFound
from io import BytesIO

from .views_templates import *

from lib.service import Service
from . import manager

static = Blueprint("static", __name__, url_prefix="/static/")
@static.route("/js/<path:path>")
async def serve_js(path):
    try:
        return await send_from_directory("lib/static/js/", file_name=path)
    except NotFound as e:
        return await missing(e)
        
controller = Blueprint("controller", __name__)

@controller.app_errorhandler(500)
async def server_died(e):
    return "<img src='https://http.cat/500.jpg'>", 500

@controller.app_errorhandler(400)
async def bad_request(e):
    return "<img src='https://http.cat/400.jpg'>", 400

@controller.app_errorhandler(404)
async def missing(e):
    return "<img src='https://http.cat/404.jpg'>", 404

def error(error_string: str):
    return jsonify({"error": error_string}), 400

def ok():
    return jsonify({"status": "ok"}), 200

async def get_status(name):
    res = await manager[name].get_status()
    return (manager[name], res)

@controller.route("/")
async def index():
    # TODO: add possibility of serivce being paused, color-danger or sth.
    online = await asyncio.gather(*[get_status(m) for m in manager])
    return await render_template("index.jinja", manager=online)

@controller.route("/add", methods=["GET", "POST"])
async def add():
    if request.method == "GET":
        return await render_template("add.jinja")
    else:
        if (data := await request.json):
            try:
                manager[data["name"]] = Service(data["name"], data["address"])
                return ok()
            except KeyError:
                return error()
    return error()

@controller.route("/manage/<string:name>", methods=["GET", "POST"])
async def manage(name):
    try:
        service = manager[name]
    except KeyError as e:
        return await missing(e)
    
    if request.method == "GET":
        if (data := await service.get_status()):
            if data["type"] == "aggregator":
                #* im so fucking bored of doing this, gonna do this in a pretty weird way
                AGGREGATOR_REMOVE[0][-1] = list(data["status"].keys())
                AGGREGATOR_CHANGE[0][-1] = AGGREGATOR_REMOVE[0][-1]
            return await render_template("manage.jinja", 
                         service=service,
                         data=data,
                         forms={"GENERATOR_GETTER": GENERATOR_GETTER,
                                "GENERATOR_SENDER": GENERATOR_SENDER,
                                "AGGREGATOR_ADD": AGGREGATOR_ADD,
                                "AGGREGATOR_REMOVE": AGGREGATOR_REMOVE,
                                "AGGREGATOR_CHANGE": AGGREGATOR_CHANGE,
                                "FILTER_CHANGE": FILTER_CHANGE,
                                "FILTER_SENDER": FILTER_SENDER,
                                "FILTER_GETTER": FILTER_GETTER,
                                "AGGREGATOR_GRAPH_CHANGE": AGGREGATOR_GRAPH_CHANGE})
    else:
        if (data := await request.json):
            if data["type"] == "generator":
                if data["action"] == "change_sender":
                    ret = await Generator.handle_change_sender(service, data["form"])
                elif data["action"] == "change_getter":
                    ret = await Generator.handle_change_getter(service, data["form"])
                elif data["action"] == "toggle_pause":
                    ret = await Generator.handle_toggle_pause(service, data["form"])
                else:
                    return error("unknown action")
            elif data["type"] == "aggregator":
                if data["action"] == "add":
                    ret = await Aggregator.handle_add_aggregator(service, data["form"])
                elif data["action"] == "change":
                    ret = await Aggregator.handle_change_aggregator(service, data["form"])
                elif data["action"] == "remove":
                    ret = await Aggregator.handle_remove_aggregator(service, data["form"])
                else:
                    return error("unknown action")

            elif data["type"] == "generator-filter":
                if data["action"] == "toggle_pause":
                    ret = await FilterGenerator.handle_toggle_pause(service, data["form"])
                elif data["action"] == "change_sender":
                    ret = await FilterGenerator.handle_change_sender(service, data["form"])
                elif data["action"] == "change_getter":
                    ret = await FilterGenerator.handle_change_getter(service, data["form"])
                elif data["action"] == "change_filter":
                    ret = await FilterGenerator.handle_change_filter(service, data["form"])
                else:
                    return error("unknown action")
            elif data["type"] == "graphing-aggregator":
                if data["action"] == "change":
                    ret = await GraphingAggregator.handle_change(service, data["form"])
                else:
                    return error("unknown action")
    
            if ret:
                return ok()

        return error("json data missing")
    return redirect("/")
        
@controller.route("/manage/<string:name>/graph", methods=["GET", "POST"])
async def get_graph(name):
    try:
        service = manager[name]
    except KeyError as e:
        return await missing(e)

    if (image := await service.get("/api/get_graph", await request.json)):
        return await send_file(BytesIO(image), "image/svg+xml"), 200
    else:
        return error("bad request")

iot/lista_5/lib/templates/add.jinja
{% extends "include/main.jinja" %}
{% block title %} Add {% endblock title %}
{% block content %}
<div class="row mt-5 bg-light p-3">
    <h3>Add new service</h3>
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <form id="add">
            <div class="mb-3">
                <label for="name" class="form-label">Name:</label>
                <input required type="text" class="form-control" name="name">
                <div class="form-text">Name of service</div>
            </div>
            <div class="mb-3">
                <label class="form-label" for="address">Address:</label>
                <input required type="text" class="form-control" name="address">
                <div class="form-text">Address of the service</div>
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-outline-dark">Submit</button>
            </div>
        </form>
    </div>
    <div class="col-lg-3"></div>
</div>
{% endblock %}
{% block scripts %}
<script src="/static/js/add.js"></script>
{% endblock %}

iot/lista_5/lib/templates/include/macros.jinja
{%- macro render_badge(text, type, dark_text=False, special_style=None) -%}
    <span class="badge bg-{{type}} {{ 'text-dark' if dark_text else '' }}" style="{{ special_style if special_style}}">{{text}}</span>
{%- endmacro -%}

{% macro _render_card_title(running, service) %}
    <h4 class="card-title" style="font-family: monospace;">
    {{service.name}}
    {% if running %}
        {{ render_badge("Running", "success") }}
    {% else %}
        {{ render_badge("No connection", "danger")}}
    {% endif %}
    </h4>
{% endmacro %}

{% macro _render_card_text(type, service) %}
    <div class="card-text font-monospace">
        {% if type != None %}
            <p class="mb-1"><a href="{{service.address}}">{{service.address}}</a></p>
        {% else %}
            <p class="mb-1"><span>{{service.address}}</span></p>
        {% endif %}

        <p class="mb-0">{{ render_badge("Type", "info", True, "border-top-right-radius: 0; border-bottom-right-radius: 0") }}
            {%- if type == "generator" -%}
                {{ render_badge("Generator", "primary", special_style="border-top-left-radius: 0; border-bottom-left-radius: 0") }}
            {%- elif type == "aggregator" -%}
                {{ render_badge("Aggregator", "secondary", special_style="border-top-left-radius: 0; border-bottom-left-radius: 0") }}
            {%- elif type == "generator-filter" -%}
                {{ render_badge("Generator filter", "warning", True, special_style="border-top-left-radius: 0; border-bottom-left-radius: 0") }}
            {%- elif type == "graphing-aggregator" -%}
                {{ render_badge("graphing-aggregator", "success", special_style="border-top-left-radius: 0; border-bottom-left-radius: 0") }}
            {%- else -%}
                {{ render_badge("Unknown?!", "dark", special_style="border-top-left-radius: 0; border-bottom-left-radius: 0") }}
            {%- endif -%}
        </p>
    </div>
{% endmacro %}}


{% macro _render_card_footer(is_alive, name) %}
    <div class="card-footer">
    {% if is_alive %}
        <a class="btn btn-success text-white" href="{{ url_for('controller.manage', name=name) }}">Manage</a>
    {% else %}
        <a class="btn btn-danger disabled text-white">Manage</a>
    {% endif %}
    </div>
{% endmacro %}


{% macro render_card(card) %}
    <div class="card shadow h-100">
        <div class="card-body">
            {{ _render_card_title(card[1], card[0]) }}
            {% if card[1] and "type" in card[1] %}
                {{ _render_card_text(card[1]["type"], card[0]) }}
            {% else %}
                {{ _render_card_text(None, card[0])}}
            {% endif %}
        </div>
        {{ _render_card_footer(card[1], card[0].name) }}
    </div>
{% endmacro %}

iot/lista_5/lib/templates/include/main.jinja
<!doctype html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎯</text></svg>">
        <title>{% block title %} guno? {% endblock title %}</title>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid p-0">
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="/">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{{ url_for('controller.add') }}">Add</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <main class="container">
        {% block content %}{% endblock content %}
        </main>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        {% block scripts %}
        {% endblock scripts %}
    </body>
</html>

iot/lista_5/lib/templates/include/manage_base.jinja
{% extends "include/main.jinja" %}
{% from "include/macros.jinja" import render_badge with context %}

{% macro render_manage_title(name, type, running) %}
    <h1 style="font-family: monospace;">
    {{ name }}
    {% if type == "generator" or type == "generator-filter" %}
        {% if running %}
            <button type="button" class="btn btn-success" id="button">Running</button>
        {% else %}
            <button type="button" class="btn btn-warning" id="button">Paused</button>
        {% endif %}
    {% elif type == "aggregator" or type == "graphing-aggregator" %}
        {{ render_badge("Running", "success") }}
    {% else %}
        {{ render_badge("Unknown", "danger", True)}}
    {% endif %}

    </h1>
{% endmacro %}

{% macro render_subservices(data) %}
    {% if data is mapping%}
        {% for name, item in data.items() %}
            {% if item is mapping %}
                {{- render_badge(name, "dark") -}}:
                <div class="ms-4">
                    {{ render_subservices(item) }}
                </div>
            {% elif item is sequence and item is not string %}
                {{- render_badge(name, "dark") -}}:
                {% for single in item %}
                    <div class="ms-4">
                        {{ render_subservices(single) }}
                    </div>
                {% endfor %}
            {% else %}
                <p class="m-0">
                {{- render_badge(name, "info", special_style="border-top-right-radius: 0; border-bottom-right-radius: 0" ) -}}
                {{- render_badge(item, "secondary", special_style="border-top-left-radius: 0; border-bottom-left-radius: 0") -}}
                </p>
            {% endif %}
        {% endfor %}
    {% else %}
        {{- render_badge(data, "info") -}}
    {% endif %}
{% endmacro %}


{% macro _render_form(form_id, items) %}
{# form_id: str, items = [(name, type, required, label, help, special_tags, _)] #}
    <form id="{{form_id}}" class="d-flex flex-column">
        {% for name, type, required, label, help, special_tags, _ in items %}
            <div class="mb-3">
                {% if type == "checkbox" %}
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="true" id="{{ name }}" name="{{ name }}">
                        <label class="form-check-label" for="{{ name }}" {{ special_tags or "" }}>{{label}}</label>
                    </div>
                {% elif type == "select" %}
                    <label for="{{ name }}" class="form-label">{{label}}</label>
                    <select class="form-select" name="{{ name }}" id="{{ name }}" {{ 'required' if required else "" }} {{ special_tags or "" }}>
                        {% for item in _ %}
                            <option value="{{ item }}">{{ item }}</option>
                        {% endfor %}
                    </select>
                    <div id="{{ name }}-help" class="form-text">{{ help }}</div>
                {% else %}
                    <label for="{{ name }}" class="form-label">{{ label }}</label>
                    <input type="{{ type }}" class="form-control" {{ 'required' if required else "" }} id="{{ name }}" name="{{ name }}" {{ special_tags or "" }}>
                    <div id="{{ name }}-help" class="form-text">{{ help }}</div>
                {% endif %}
            </div>
        {% endfor %}
        <div class="mt-3 align-self-end">
            <button type="submit" class="btn btn-outline-dark">Submit</button>
        </div>
    </form>


{% endmacro %}

{% macro render_forms(type, dict) %}
    {% if type == "generator" %}
        <div class="col-lg-6">
            <h4>Data getter:</h4>
            {{ _render_form("getter", dict["GENERATOR_GETTER"]) }}
        </div>
        <div class="col-lg-6">
            <h4>Data sender:</h4>
            {{ _render_form("sender", dict["GENERATOR_SENDER"]) }}
        </div>
    {% elif type == "aggregator" %}
        <div class="col-lg-4">
            <h4>Add aggregator</h4>
            {{ _render_form("add", dict["AGGREGATOR_ADD"])}}
        </div>
        <div class="col-lg-4">
            <h4>Change aggregator</h4>
            {{ _render_form("change", dict["AGGREGATOR_CHANGE"])}}
        </div>
        <div class="col-lg-4">
            <h4>Remove aggregator</h4>
            {{ _render_form("remove", dict["AGGREGATOR_REMOVE"])}}
        </div>
    {% elif type == "generator-filter" %}
        <div class="col-lg-4">
            <h4>Data getter:</h4>
            {{ _render_form("getter", dict["FILTER_GETTER"]) }}
        </div>
        <div class="col-lg-4">
            <h4>Data sender:</h4>
            {{ _render_form("sender", dict["FILTER_SENDER"]) }}
        </div>
        <div class="col-lg-4">
            <h4>Data filter:</h4>
            {{ _render_form("filter", dict["FILTER_CHANGE"]) }}
        </div>
    {% elif type == "graphing-aggregator" %}
      <div class="col-lg-4">
            <h4>Aggregator</h4>
            {{ _render_form("part-aggregator", dict["AGGREGATOR_GRAPH_CHANGE"]) }}
        </div>
        <div class="col-lg-8">
            <h4>Graph:</h4>
            <div id="graph"></div>
        </div>
    {% endif %}
{% endmacro %}

iot/lista_5/lib/templates/index.jinja
{% from "include/macros.jinja" import render_card with context %}

{% extends "include/main.jinja" %}
{% block title %} index {% endblock title %}

{% block content %}
<div class="row mt-5">
{% for service in manager %}
    <div class="col-lg-4 mb-3">
        {{ render_card(service) }}
    </div>
{% endfor %}
</div>
{% endblock content %}

iot/lista_5/lib/templates/manage.jinja
{# Passed arguments here should include: status and service #}

{% from "include/manage_base.jinja" import render_manage_title with context %}
{% from "include/manage_base.jinja" import render_subservices with context %}
{% from "include/manage_base.jinja" import render_forms with context %}

{% extends "include/main.jinja" %}

{% block title %}{{ data["name"] if data["name"] else service.name }}{% endblock title %}
{% block content %}
<div class="row mt-5 bg-light p-3">
    <div class="col-lg-12">
        {% if "name" in data %} {# TODO: implement better way of checking type #}
            {{ render_manage_title(data["name"], data["type"], data["running"]) }}
                {% if data["type"] == "generator-filter" %}
                    <p>Currently on {{data["iterations"]}}/{{data["successful_iterations"]}} iteration with period of {{data["period"]}}s.</p>
                {% else %}
                    <p>Currently on {{data["iterations"]}} iteration with period of {{data["period"]}}s.</p>
                {% endif %}
        {% elif data["type"] == "aggregator" %}
            {{ render_manage_title(service.name, data["type"], False) }}
            <p>Curently running {{ data["status"] | length }} sub-aggregators.</p>
        {% elif data["type"]  == "graphing-aggregator" %}
            {{ render_manage_title(service.name, data["type"], False) }}
        {% else %}
            {{ render_manage_title(service.name, None, False) }}
        {% endif %}
        <div class="row">
            {% if data["type"] == "generator" %}
                {% for subs in ("getter", "sender") %}
                    <div class="col-lg-6 font-monospace">
                        <h4>Data {{subs}}:</h4>
                        {{ render_subservices(data[subs]) }}
                    </div>
                {% endfor %}
            {% elif data["type"] == "generator-filter" %}
                <div class="col-lg-4 font-monospace">
                    <h4>Current paths:</h4>
                    {{render_subservices(data["filter"])}}
                </div>
                <div class="col-lg-4 font-monospace">
                    <h4>Sender:</h4>
                    {{render_subservices(data["sender"])}}
                </div>
                <div class="col-lg-4 font-monospace">
                    <h4>Getter:</h4>
                    {{render_subservices(data["getter"])}}
                </div>
            {% elif data["type"] == "aggregator" %}
                {% for subs, item in data["status"].items() %}
                    <div class="col-lg-4">
                        <h4>Subaggregator '<a href="{{ service.address + '/' + subs }}" class="font-monospace">{{subs}}</a>':</h4>
                        <div class="font-monospace">
                            {{ render_subservices(item) }}
                        </div>
                    </div>
                {% endfor %}
            {% elif data["type"] == "graphing-aggregator" %}
                <div class="col-lg-6">
                    <h4>Graph</h4>
                    {{ render_subservices(data["status"].pop("graph")) }}
                </div>
                <div class="col-lg-6">
                    <h4>Aggregator</h4>
                    {{ render_subservices(data["status"]) }}
                </div>
            {% endif %}
        </div>
    </div>
</div>
<div class="row mt-5 bg-light p-3">
    <div class="col-lg-12">
        <h2 class="font-monospace">Edit:</h2>
        <div class="row">
            {{ render_forms(data["type"], forms) }}
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts %}
<script src="/static/js/manage_base.js"></script>
{% if data["type"] == "generator" %}
<script src="/static/js/manage_generator.js"></script>
{% elif data["type"] == "aggregator" %}
<script src="/static/js/manage_aggregator.js"></script>
{% elif data["type"] == "generator-filter" %}
<script src="/static/js/manage_generator_filter.js"></script>
{% elif data["type"] == "graphing-aggregator" %}
<script src="/static/js/manage_graphing_aggregator.js"></script>
{% else %}

{% endif %}
{% endblock scripts %}